### ISSUE TITLE
so no work.

### ISSUE THREAD

**Issue by erikpedra** [Theyka/Turnstile-Solver#4]
I tried nodepay login to get captcha token, it doesn't work.

result = await get_turnstile_token(
            headless=True,
            url="https://app.nodepay.ai/login",
            sitekey="0x4AAAAAAAx1CyDNL8zOEPe7"
        )
        print(result)

[discord.cyberious.xyz] [04:19:30] [Solving captcha...] ⣯[discord.cyberious.xyz] [04:19:47] [Failure] -> Failed to retrieve Turnstile value.
[discord.cyberious.xyz] [04:19:30] [Solving captcha...] ⢿
{'turnstile_value': None, 'elapsed_time_seconds': 17.074, 'status': 'failure', 'reason': 'Max attempts reached without token retrieval'}

**Comment by Theyka** [comment]
set the headless to False and it will work

**Comment by erikpedra** [comment]
> set the headless to False and it will work

Yes it works, but it will be very annoying if it displays the browser.

**Comment by Theyka** [comment]
> > set the headless to False and it will work
> 
> Yes it works, but it will be very annoying if it displays the browser.

can't do anything about that, setting headless to true makes you get caught to turnstile
